root: true
env:
  es2020: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'prettier'
rules:
  no-unused-vars: warn
  no-console: warn
  prefer-const:
    - warn
    - destructuring: all
overrides:
  - files: ['*.astro']
    parser: astro-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions: ['.astro']
  - files: ['*.astro', '*.ts', '.*tsx']
    rules:
      no-undef: off
      no-duplicate-imports: off
      import/no-duplicates: error
      no-unused-vars: off
      '@typescript-eslint/no-unused-vars': off # tsserver handles better
      no-redeclare: off
      '@typescript-eslint/no-redeclare': error
